import { ROUTE_CAPABILITY_IDS, TECHNICAL_EXTENSION_CAPABILITY_IDS } from './capability-ids.js';
import { ROUTE_IDS, type RouteDefinition, type RouteId } from './types.js';

interface RouteInput extends Omit<RouteDefinition, 'capabilityIds'> {
  readonly capabilityIds?: readonly string[];
}

function route(input: RouteInput): RouteDefinition {
  const technical = TECHNICAL_EXTENSION_CAPABILITY_IDS[input.routeId] ?? [];
  return {
    ...input,
    capabilityIds: input.capabilityIds ?? [...ROUTE_CAPABILITY_IDS[input.routeId], ...technical],
  };
}

export const ROUTE_CATALOG: readonly RouteDefinition[] = [
  route({
    routeId: 'R01',
    name: 'ARTE_GRAFICA',
    purpose: 'Criar e adaptar peças visuais governadas pela marca.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-05',
    auxiliaryAgents: ['AG-01', 'AG-03', 'AG-06', 'AG-07', 'AG-04'],
    subflows: [
      'CRIACAO_DO_ZERO',
      'ADAPTACAO_DE_TEMPLATE',
      'RESIZE',
      'CAMPANHA',
      'FLYER',
      'CARD',
      'MENU',
      'CONVITE',
      'SINALIZACAO',
      'APRESENTACAO',
      'CRIATIVO_DE_ANUNCIO',
      'STORY',
      'FEED',
      'REEL_COVER',
    ],
    initialState: 'BRIEF_REQUIRED',
    terminalStates: ['REVIEW', 'APPROVED', 'READY_FOR_PUBLICATION'],
  }),
  route({
    routeId: 'R02',
    name: 'PUBLICAR_IMAGEM',
    purpose: 'Preparar, publicar e reconciliar mídia social com confirmação do provider.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-08',
    auxiliaryAgents: ['AG-01', 'AG-06', 'AG-07', 'AG-04', 'AG-16'],
    subflows: [
      'IMAGEM_UNICA',
      'CAROUSEL',
      'PUBLICACAO_IMEDIATA',
      'PUBLICACAO_PRE_APROVADA',
      'RETRY_POS_FALHA',
      'PROVIDER_RECONCILIATION',
      'PUBLICACAO_MANUAL_ASSISTIDA',
    ],
    initialState: 'READY_FOR_VALIDATION',
    terminalStates: ['PUBLISHED', 'MANUAL_HANDOFF_REQUIRED', 'BLOCKED'],
  }),
  route({
    routeId: 'R03',
    name: 'CURADORIA_VISUAL',
    purpose: 'Selecionar e governar ativos visuais oficiais sem repetição indevida.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-06',
    auxiliaryAgents: ['AG-01'],
    subflows: [
      'SUNSET',
      'THE_PARTY',
      'GASTRONOMIA',
      'INSTITUCIONAL',
      'PESSOAS',
      'DJS',
      'ESTRUTURA',
      'BEBIDAS',
      'UGC',
      'FOTOS_PARA_ANUNCIOS',
      'BANCO_EVERGREEN',
    ],
    initialState: 'SCAN_REQUIRED',
    terminalStates: ['ASSET_SELECTED', 'NO_ELIGIBLE_ASSET'],
  }),
  route({
    routeId: 'R04',
    name: 'TRATAMENTO_IMAGEM',
    purpose: 'Tratar fotografias com fidelidade, lineage e validação de similaridade.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-07',
    auxiliaryAgents: ['AG-01'],
    subflows: [
      'TRATAMENTO_FIEL',
      'TRATAMENTO_CINEMATOGRAFICO',
      'RECUPERACAO_BAIXA_QUALIDADE',
      'REMOCAO_DE_OBJETOS',
      'AJUSTE_FEED',
      'AJUSTE_STORIES',
      'ANUNCIO',
      'IMPRESSAO',
    ],
    initialState: 'SOURCE_BINDING_REQUIRED',
    terminalStates: ['MARKETING_READY', 'QUALITY_GATE_FAILED'],
  }),
  route({
    routeId: 'R05',
    name: 'COPY',
    purpose: 'Produzir texto aderente à voz, fatos, canal e objetivo.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-04',
    auxiliaryAgents: ['AG-01', 'AG-03'],
    subflows: [
      'INSTAGRAM',
      'STORIES',
      'ANUNCIOS',
      'WHATSAPP',
      'EMAIL',
      'PAGINA_DE_VENDAS',
      'EVENTOS',
      'CRM',
      'INSTITUCIONAL',
      'COMERCIAL',
    ],
    initialState: 'BRIEF_REQUIRED',
    terminalStates: ['COPY_APPROVED'],
  }),
  route({
    routeId: 'R06',
    name: 'PLANO_EDITORIAL',
    purpose: 'Planejar slots e mix editorial com cobertura e anti-repetição.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-08',
    auxiliaryAgents: ['AG-01', 'AG-03', 'AG-06', 'AG-07', 'AG-05', 'AG-04'],
    subflows: [
      'JANELA_7_DIAS',
      'MENSAL',
      'SUNSET',
      'THE_PARTY',
      'GASTRONOMIA',
      'INSTITUCIONAL',
      'DATAS_ESPECIAIS',
      'CAMPANHAS',
      'LAST_MINUTE',
    ],
    initialState: 'WINDOW_REQUIRED',
    terminalStates: ['READY_FOR_SCHEDULING', 'SCHEDULED', 'PUBLISHED'],
  }),
  route({
    routeId: 'R07',
    name: 'CAMPANHA_MARKETING',
    purpose: 'Estruturar campanhas multicanal com objetivo, oferta, ativos, orçamento e KPIs.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-03',
    auxiliaryAgents: ['AG-01', 'AG-02', 'AG-04', 'AG-05', 'AG-06', 'AG-07', 'AG-08', 'AG-09'],
    subflows: [
      'LANCAMENTO',
      'EVENTO',
      'AWARENESS',
      'VENDAS',
      'REATIVACAO',
      'PROMOCAO',
      'BRANDING',
      'PARCERIAS',
      'INFLUENCER',
    ],
    initialState: 'BRIEF_REQUIRED',
    terminalStates: ['CAMPAIGN_READY', 'CAMPAIGN_CLOSED'],
  }),
  route({
    routeId: 'R08',
    name: 'META_ADS',
    purpose: 'Realizar estratégia, diagnóstico, auditoria e recomendação de Meta Ads.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-09',
    auxiliaryAgents: ['AG-01', 'AG-03', 'AG-04', 'AG-05', 'AG-06', 'AG-07'],
    subflows: [
      'DIAGNOSTICO',
      'PLANEJAMENTO',
      'AUDITORIA',
      'RECOMENDACAO',
      'ESTRUTURACAO',
      'LEITURA_DE_PERFORMANCE',
    ],
    initialState: 'ACCOUNT_CONTEXT_REQUIRED',
    terminalStates: ['READY_FOR_EXECUTION', 'STRATEGY_READY'],
  }),
  route({
    routeId: 'R09',
    name: 'ENGAGEMENT_SOCIAL',
    purpose: 'Ler, classificar e responder interações sociais segundo política.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-08',
    auxiliaryAgents: ['AG-01', 'AG-04', 'AG-11', 'AG-14'],
    subflows: ['COMENTARIO', 'DIRECT', 'MENCAO', 'ESCALATION'],
    initialState: 'RECEIVED',
    terminalStates: ['READY_TO_REPLY', 'SENT', 'ESCALATED_TO_HUMAN'],
  }),
  route({
    routeId: 'R10',
    name: 'COMERCIAL_PARCERIAS',
    purpose: 'Conduzir leads, propostas, parcerias, patrocínios e eventos privados.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-10',
    auxiliaryAgents: ['AG-01', 'AG-04', 'AG-05', 'AG-12', 'AG-14'],
    subflows: [
      'PATROCINADOR',
      'PARCERIA',
      'AGENCIA',
      'INFLUENCER',
      'EVENTO_PRIVADO',
      'GRUPO',
      'EMPRESA',
      'PRODUTOR',
      'OPERADOR_TURISTICO',
    ],
    initialState: 'REQUESTED',
    terminalStates: ['PROPOSAL_READY', 'CLOSED_WON', 'CLOSED_LOST'],
  }),
  route({
    routeId: 'R11',
    name: 'APRESENTACAO',
    purpose: 'Criar apresentações profissionais e verificadas.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-05',
    auxiliaryAgents: ['AG-01', 'AG-10', 'AG-03', 'AG-04', 'AG-06', 'AG-07'],
    subflows: [
      'COMERCIAL',
      'PATROCINADOR',
      'INSTITUCIONAL',
      'EVENTO',
      'RELATORIO',
      'PITCH',
      'TREINAMENTO',
    ],
    initialState: 'BRIEF_REQUIRED',
    terminalStates: ['DECK_READY'],
  }),
  route({
    routeId: 'R12',
    name: 'ORGANIZACAO_DRIVE',
    purpose: 'Organizar recursos do Drive preservando IDs, canonicalidade e histórico.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-01',
    auxiliaryAgents: ['AG-06', 'AG-15'],
    subflows: [
      'CLASSIFICACAO',
      'RENOMEACAO',
      'MOVIMENTACAO',
      'DEDUPLICACAO',
      'ARQUIVAMENTO',
      'PERMISSOES',
    ],
    initialState: 'SCAN_REQUIRED',
    terminalStates: ['CLASSIFIED', 'MOVED', 'AUDITED'],
  }),
  route({
    routeId: 'R13',
    name: 'OPERACOES_RESTRITAS',
    purpose: 'Executar somente abertura, fechamento, checklists e eventos.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-11',
    auxiliaryAgents: ['AG-01', 'AG-03', 'AG-10', 'AG-12'],
    subflows: [
      'ABERTURA',
      'FECHAMENTO',
      'CHECKLIST_DIARIO',
      'PREPARACAO_DE_EVENTO',
      'OPERACAO_DE_EVENTO',
      'INCIDENTE',
    ],
    initialState: 'CHECKLIST_REQUIRED',
    terminalStates: ['OPERATION_CHECKLIST_READY', 'OPERATION_STATUS_READY'],
  }),
  route({
    routeId: 'R14',
    name: 'FINANCEIRO_GERENCIAL',
    purpose: 'Gerir eventos, fluxo de caixa, orçamento, indicadores e relatórios sem pagamentos.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-12',
    auxiliaryAgents: ['AG-01', 'AG-02', 'AG-11'],
    subflows: ['EVENTOS', 'FLUXO_DE_CAIXA', 'ORCAMENTO', 'INDICADORES', 'RELATORIOS'],
    initialState: 'SOURCE_DATA_REQUIRED',
    terminalStates: ['FINANCIAL_ANALYSIS_READY', 'FINANCIAL_REPORT_READY'],
  }),
  route({
    routeId: 'R15',
    name: 'PESSOAS_RH',
    purpose: 'Apoiar papéis, onboarding, treinamento, escalas e comunicação de pessoas.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-13',
    auxiliaryAgents: ['AG-01'],
    subflows: ['PAPEIS', 'ONBOARDING', 'TREINAMENTO', 'ESCALAS', 'PERFORMANCE', 'COMUNICACAO'],
    initialState: 'REQUESTED',
    terminalStates: ['HR_OUTPUT_READY'],
  }),
  route({
    routeId: 'R16',
    name: 'JURIDICO_COMPLIANCE',
    purpose:
      'Apoiar revisão documental, direitos, LGPD e compliance com escalonamento profissional.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-14',
    auxiliaryAgents: ['AG-01'],
    subflows: ['CONTRATO', 'DIREITO_DE_IMAGEM', 'MARCA', 'LGPD', 'CONSENTIMENTO', 'COMPLIANCE'],
    initialState: 'SOURCE_DOCUMENT_REQUIRED',
    terminalStates: ['COMPLIANCE_REVIEW_READY', 'ESCALATED_TO_COUNSEL'],
  }),
  route({
    routeId: 'R17',
    name: 'TECNOLOGIA_AUTOMACAO',
    purpose:
      'Diagnosticar e configurar integrações, runtime, workers, filas e automações genéricas.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-15',
    auxiliaryAgents: ['AG-01'],
    subflows: [
      'INTEGRACAO',
      'WEBHOOK',
      'RUNTIME',
      'DATABASE',
      'WORKER',
      'SCHEDULER',
      'FEATURE_FLAG',
      'AUTOMACAO',
    ],
    initialState: 'INSPECTION_REQUIRED',
    terminalStates: ['TECH_PLAN_READY', 'TECH_CHANGE_VALIDATED'],
  }),
  route({
    routeId: 'R18',
    name: 'SOCIAL_ANALYTICS',
    purpose: 'Transformar métricas sociais reais em análise comparável.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-08',
    auxiliaryAgents: ['AG-01', 'AG-02', 'AG-03', 'AG-09'],
    subflows: ['ACCOUNT', 'MEDIA', 'STORY', 'REEL', 'PERIOD_COMPARISON', 'DASHBOARD', 'REPORT'],
    initialState: 'METRICS_REQUIRED',
    terminalStates: ['SOCIAL_PERFORMANCE_ANALYSIS_READY'],
  }),
  route({
    routeId: 'R19',
    name: 'MARKETING_AUTOPILOT_HORARIO',
    purpose: 'Orquestrar o ciclo horário cognitivo por estado e prioridade.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-01',
    auxiliaryAgents: [
      'AG-03',
      'AG-08',
      'AG-06',
      'AG-07',
      'AG-05',
      'AG-04',
      'AG-09',
      'AG-15',
      'AG-16',
    ],
    subflows: [
      'PLANEJAMENTO',
      'PRODUCAO',
      'APROVACAO',
      'SCHEDULING',
      'PUBLICACAO',
      'ENGAGEMENT',
      'MEDICAO',
      'RECOVERY',
    ],
    initialState: 'CYCLE_STARTED',
    terminalStates: ['CYCLE_COMPLETE', 'BLOCKED'],
  }),
  route({
    routeId: 'R20',
    name: 'VIDEO_REELS_CREATIVE_PRODUCTION',
    purpose:
      'Produzir Stories e vídeos curtos com master-first, lineage, direitos, acessibilidade e quality gates.',
    priority: 'UNSPECIFIED',
    primaryAgent: 'AG-05',
    auxiliaryAgents: ['AG-01', 'AG-04', 'AG-06', 'AG-07', 'AG-08'],
    subflows: [
      'SUNSET',
      'THE_PARTY',
      'CONTAGEM_REGRESSIVA',
      'CTA',
      'PROVA_SOCIAL',
      'VENDA',
      'AGENDA',
      'EVENTO_COMECANDO_AGORA',
      'POS_EVENTO',
      'REEL',
      'STORY_VIDEO',
      'REPURPOSING',
      'SUBTITLES',
      'THUMBNAIL',
    ],
    initialState: 'PLAN_REQUIRED',
    terminalStates: [
      'VIDEO_READY',
      'REEL_READY',
      'STORY_READY',
      'APPROVED',
      'SCHEDULED',
      'PUBLISHED',
    ],
  }),
  route({
    routeId: 'R21',
    name: 'GOVERNANCE_DRIFT_RECONCILIATION',
    purpose: 'Detectar e reconciliar divergências Drive, GitHub, registries, runtime e provider.',
    priority: 'P0',
    primaryAgent: 'AG-15',
    auxiliaryAgents: ['AG-01', 'AG-16'],
    subflows: ['FULL_SCAN', 'TARGETED_SCAN', 'AUTO_RECONCILIATION', 'HUMAN_DECISION'],
    initialState: 'SCAN',
    terminalStates: ['RECONCILED', 'BLOCKED_PENDING_HUMAN_DECISION'],
  }),
  route({
    routeId: 'R22',
    name: 'CAPABILITY_LIFECYCLE_VALIDATION',
    purpose: 'Validar evidência e promover, rebaixar, suspender ou remover capabilities.',
    priority: 'P0',
    primaryAgent: 'AG-15',
    auxiliaryAgents: ['AG-01', 'AG-16'],
    subflows: ['PROMOTION', 'DEMOTION', 'SUSPENSION', 'RESUME', 'DEPRECATION', 'REMOVAL'],
    initialState: 'PLANNED',
    terminalStates: ['PRODUCTION_VALIDATED', 'SUSPENDED', 'DEPRECATED', 'REMOVED'],
  }),
  route({
    routeId: 'R23',
    name: 'RELEASE_DEPLOYMENT_ROLLBACK',
    purpose: 'Controlar branch, PR, Quality Gate, merge, deploy, smoke, evidência e rollback.',
    priority: 'P0',
    primaryAgent: 'AG-15',
    auxiliaryAgents: ['AG-01'],
    subflows: ['STANDARD_RELEASE', 'HOTFIX', 'ROLLBACK'],
    initialState: 'CHANGE_REQUESTED',
    terminalStates: ['COMPLETED', 'ROLLBACK_VERIFIED', 'FAILED'],
  }),
  route({
    routeId: 'R24',
    name: 'SECURITY_AND_SUPPLY_CHAIN',
    purpose: 'Validar proteção de repositório, IAM, secrets, dependências, scans e SBOM.',
    priority: 'P1',
    primaryAgent: 'AG-15',
    auxiliaryAgents: ['AG-01', 'AG-14'],
    subflows: [
      'REPOSITORY_POSTURE',
      'IDENTITY_ACCESS',
      'SECRETS',
      'DEPENDENCIES',
      'CONTAINER',
      'SBOM',
      'DRIVE_ACL',
    ],
    initialState: 'SCAN',
    terminalStates: ['SECURITY_POSTURE_VALIDATED', 'BLOCKED'],
  }),
  route({
    routeId: 'R25',
    name: 'OBSERVABILITY_AND_INCIDENT_RESPONSE',
    purpose: 'Detectar, triar, mitigar e encerrar incidentes com postmortem.',
    priority: 'P1',
    primaryAgent: 'AG-15',
    auxiliaryAgents: ['AG-01', 'AG-16'],
    subflows: [
      'HEALTH_TRIAGE',
      'PROVIDER_INCIDENT',
      'WORKER_INCIDENT',
      'DEAD_LETTER_RECOVERY',
      'POSTMORTEM',
    ],
    initialState: 'DETECTED',
    terminalStates: ['RESOLVED', 'POSTMORTEM_COMPLETE'],
  }),
  route({
    routeId: 'R26',
    name: 'BACKUP_RESTORE_DISASTER_RECOVERY',
    purpose: 'Comprovar backup, restauração, integridade, RPO e RTO por exercícios reais.',
    priority: 'P1',
    primaryAgent: 'AG-15',
    auxiliaryAgents: ['AG-01'],
    subflows: ['BACKUP_VERIFICATION', 'RESTORE_TEST', 'DR_EXERCISE'],
    initialState: 'POLICY_INSPECTION',
    terminalStates: ['RECOVERY_VALIDATED', 'GAPS_RECORDED'],
  }),
  route({
    routeId: 'R27',
    name: 'APPROVAL_GOVERNANCE',
    purpose: 'Criar, emitir, verificar, consumir, revogar, expirar e auditar ApprovalRecords.',
    priority: 'P0',
    primaryAgent: 'AG-01',
    auxiliaryAgents: ['AG-15', 'AG-14'],
    subflows: ['REQUEST_ISSUE', 'VERIFICATION', 'CONSUMPTION', 'REVOCATION_EXPIRATION', 'AUDIT'],
    initialState: 'REQUESTED',
    terminalStates: ['CONSUMED', 'REVOKED', 'EXPIRED'],
  }),
  route({
    routeId: 'R28',
    name: 'META_ADS_CONTROLLED_LIFECYCLE',
    purpose: 'Executar o ciclo completo e controlado de campanhas pagas com guardrails.',
    priority: 'P1',
    primaryAgent: 'AG-09',
    auxiliaryAgents: ['AG-01', 'AG-03', 'AG-04', 'AG-05', 'AG-06', 'AG-07', 'AG-15', 'AG-16'],
    subflows: [
      'CAMPAIGN_CREATION',
      'ADSET_MANAGEMENT',
      'CREATIVE_MANAGEMENT',
      'AD_MANAGEMENT',
      'ACTIVATION',
      'BUDGET_CHANGE',
      'MONITORING',
      'OPTIMIZATION',
      'CLOSURE',
    ],
    initialState: 'PLAN',
    terminalStates: ['CLOSE', 'REPORT', 'BLOCKED'],
  }),
  route({
    routeId: 'R29',
    name: 'CONTENT_ITEM_LIFECYCLE',
    purpose: 'Governar um conteúdo individual do planejamento à medição.',
    priority: 'P2',
    primaryAgent: 'AG-08',
    auxiliaryAgents: ['AG-01', 'AG-04', 'AG-05', 'AG-06', 'AG-07', 'AG-16'],
    subflows: [
      'SINGLE_IMAGE',
      'CAROUSEL',
      'STORY',
      'REEL',
      'AD_CREATIVE',
      'VERSIONING',
      'VARIANT',
      'CHANNEL_ADAPTATION',
      'LOCALIZATION',
      'REPURPOSING',
      'EVENT_LINKAGE',
      'EXPERIMENT_LINKAGE',
    ],
    initialState: 'PLANNED',
    terminalStates: ['MEASURED', 'ARCHIVED', 'CANCELED'],
  }),
  route({
    routeId: 'R30',
    name: 'SOCIAL_ENGAGEMENT_LIFECYCLE',
    purpose: 'Governar comentários e Directs da ingestão à confirmação ou escalonamento.',
    priority: 'P2',
    primaryAgent: 'AG-08',
    auxiliaryAgents: ['AG-01', 'AG-04', 'AG-11', 'AG-14', 'AG-16'],
    subflows: [
      'ELOGIO',
      'DUVIDA',
      'PRECO',
      'HORARIO',
      'LOCALIZACAO',
      'RESERVA',
      'RECLAMACAO',
      'CRISE',
      'SPAM',
      'PARCERIA',
      'LEAD',
      'INFLUENCER',
      'IMPRENSA',
      'VIP',
    ],
    initialState: 'RECEIVED',
    terminalStates: ['PROVIDER_CONFIRMED', 'ESCALATED_TO_HUMAN', 'CLOSED'],
  }),
  route({
    routeId: 'R31',
    name: 'PERFORMANCE_FEEDBACK_OPTIMIZATION',
    purpose: 'Transformar métricas reais em hipóteses, padrões validados e aprendizados aprovados.',
    priority: 'P2',
    primaryAgent: 'AG-09',
    auxiliaryAgents: ['AG-01', 'AG-02', 'AG-03', 'AG-08'],
    subflows: [
      'ORGANIC_CONTENT',
      'PAID_MEDIA',
      'TIMING',
      'CREATIVE',
      'COPY',
      'AUDIENCE',
      'EXPERIMENTATION',
    ],
    initialState: 'HYPOTHESIS',
    terminalStates: ['APPROVED_LEARNING', 'REJECTED'],
  }),
  route({
    routeId: 'R32',
    name: 'MASTER_DATA_AND_REGISTRY_GOVERNANCE',
    purpose: 'Governar IDs, owners, paths, status, referências, canonicalidade e freshness.',
    priority: 'P1',
    primaryAgent: 'AG-15',
    auxiliaryAgents: ['AG-01'],
    subflows: [
      'RESOURCE_LIFECYCLE',
      'DUPLICATE_CONTROL',
      'OWNER_VALIDATION',
      'FRESHNESS',
      'REFERENCE_INTEGRITY',
      'CANONICAL_RESOLUTION',
      'WRITE_BACK',
    ],
    initialState: 'SCAN',
    terminalStates: ['WRITE_BACK', 'BLOCKED'],
  }),
];

const routeMap = new Map<RouteId, RouteDefinition>(
  ROUTE_CATALOG.map((definition) => [definition.routeId, definition] as const),
);

export function getRouteDefinition(routeId: RouteId): RouteDefinition {
  const definition = routeMap.get(routeId);
  if (!definition) throw new Error(`ROUTE_NOT_FOUND:${routeId}`);
  return definition;
}

export function validateRouteCatalog(): void {
  if (ROUTE_CATALOG.length !== ROUTE_IDS.length) throw new Error('ROUTE_CATALOG_INCOMPLETE');
  if (routeMap.size !== ROUTE_IDS.length) throw new Error('ROUTE_CATALOG_DUPLICATE_ID');
  for (const routeId of ROUTE_IDS) {
    const definition = routeMap.get(routeId);
    if (!definition) throw new Error(`ROUTE_CATALOG_MISSING:${routeId}`);
    if (definition.capabilityIds.length === 0)
      throw new Error(`ROUTE_WITHOUT_CAPABILITIES:${routeId}`);
    if (new Set(definition.capabilityIds).size !== definition.capabilityIds.length)
      throw new Error(`ROUTE_CAPABILITY_DUPLICATE:${routeId}`);
  }
}
