import type { StateMachineDefinition } from './state-machine.js';

export type SecurityState =
  | 'SCAN'
  | 'DIFF'
  | 'REMEDIATION_PLANNED'
  | 'REMEDIATING'
  | 'SECURITY_POSTURE_VALIDATED'
  | 'BLOCKED';

export const SECURITY_LIFECYCLE: StateMachineDefinition<SecurityState> = {
  id: 'R24_SECURITY_AND_SUPPLY_CHAIN',
  initialState: 'SCAN',
  terminalStates: ['SECURITY_POSTURE_VALIDATED', 'BLOCKED'],
  transitions: {
    SCAN: ['DIFF', 'SECURITY_POSTURE_VALIDATED', 'BLOCKED'],
    DIFF: ['REMEDIATION_PLANNED', 'BLOCKED'],
    REMEDIATION_PLANNED: ['REMEDIATING', 'BLOCKED'],
    REMEDIATING: ['SCAN', 'BLOCKED'],
    SECURITY_POSTURE_VALIDATED: [],
    BLOCKED: [],
  },
};

export type IncidentState =
  'DETECTED' | 'TRIAGED' | 'MITIGATING' | 'RESOLVED' | 'POSTMORTEM_COMPLETE';

export const INCIDENT_LIFECYCLE: StateMachineDefinition<IncidentState> = {
  id: 'R25_OBSERVABILITY_AND_INCIDENT_RESPONSE',
  initialState: 'DETECTED',
  terminalStates: ['POSTMORTEM_COMPLETE'],
  transitions: {
    DETECTED: ['TRIAGED'],
    TRIAGED: ['MITIGATING', 'RESOLVED'],
    MITIGATING: ['TRIAGED', 'RESOLVED'],
    RESOLVED: ['POSTMORTEM_COMPLETE'],
    POSTMORTEM_COMPLETE: [],
  },
};

export type DisasterRecoveryState =
  | 'POLICY_INSPECTION'
  | 'BACKUP_VERIFIED'
  | 'RESTORE_PLANNED'
  | 'RESTORE_TESTING'
  | 'INTEGRITY_VERIFIED'
  | 'RECOVERY_VALIDATED'
  | 'GAPS_RECORDED';

export const DISASTER_RECOVERY_LIFECYCLE: StateMachineDefinition<DisasterRecoveryState> = {
  id: 'R26_BACKUP_RESTORE_DISASTER_RECOVERY',
  initialState: 'POLICY_INSPECTION',
  terminalStates: ['RECOVERY_VALIDATED', 'GAPS_RECORDED'],
  transitions: {
    POLICY_INSPECTION: ['BACKUP_VERIFIED', 'GAPS_RECORDED'],
    BACKUP_VERIFIED: ['RESTORE_PLANNED', 'GAPS_RECORDED'],
    RESTORE_PLANNED: ['RESTORE_TESTING', 'GAPS_RECORDED'],
    RESTORE_TESTING: ['INTEGRITY_VERIFIED', 'GAPS_RECORDED'],
    INTEGRITY_VERIFIED: ['RECOVERY_VALIDATED', 'GAPS_RECORDED'],
    RECOVERY_VALIDATED: [],
    GAPS_RECORDED: [],
  },
};

export type MetaAdsLifecycleState =
  | 'PLAN'
  | 'PREPARE'
  | 'VALIDATE'
  | 'APPROVAL'
  | 'CREATE_PAUSED'
  | 'PROVIDER_READBACK'
  | 'READY_FOR_ACTIVATION'
  | 'ACTIVATE'
  | 'MONITOR'
  | 'ADJUST'
  | 'PAUSE'
  | 'CLOSE'
  | 'REPORT'
  | 'BLOCKED';

export const META_ADS_LIFECYCLE: StateMachineDefinition<MetaAdsLifecycleState> = {
  id: 'R28_META_ADS_CONTROLLED_LIFECYCLE',
  initialState: 'PLAN',
  terminalStates: ['REPORT', 'BLOCKED'],
  transitions: {
    PLAN: ['PREPARE', 'BLOCKED'],
    PREPARE: ['VALIDATE', 'BLOCKED'],
    VALIDATE: ['APPROVAL', 'BLOCKED'],
    APPROVAL: ['CREATE_PAUSED', 'BLOCKED'],
    CREATE_PAUSED: ['PROVIDER_READBACK', 'BLOCKED'],
    PROVIDER_READBACK: ['READY_FOR_ACTIVATION', 'BLOCKED'],
    READY_FOR_ACTIVATION: ['ACTIVATE', 'PAUSE', 'CLOSE', 'BLOCKED'],
    ACTIVATE: ['MONITOR', 'BLOCKED'],
    MONITOR: ['ADJUST', 'PAUSE', 'CLOSE', 'BLOCKED'],
    ADJUST: ['MONITOR', 'PAUSE', 'BLOCKED'],
    PAUSE: ['MONITOR', 'CLOSE', 'BLOCKED'],
    CLOSE: ['REPORT'],
    REPORT: [],
    BLOCKED: [],
  },
};

export type ContentItemState =
  | 'PLANNED'
  | 'BRIEFED'
  | 'ASSET_SELECTED'
  | 'MASTER_READY'
  | 'COPY_READY'
  | 'CREATIVE_READY'
  | 'QUALITY_PASSED'
  | 'APPROVED'
  | 'READY_FOR_SCHEDULING'
  | 'TOCA_SCHEDULED'
  | 'PUBLISHED'
  | 'MEASURED'
  | 'ARCHIVED'
  | 'CANCELED';

export const CONTENT_ITEM_LIFECYCLE: StateMachineDefinition<ContentItemState> = {
  id: 'R29_CONTENT_ITEM_LIFECYCLE',
  initialState: 'PLANNED',
  terminalStates: ['ARCHIVED', 'CANCELED'],
  transitions: {
    PLANNED: ['BRIEFED', 'CANCELED'],
    BRIEFED: ['ASSET_SELECTED', 'CANCELED'],
    ASSET_SELECTED: ['MASTER_READY', 'CANCELED'],
    MASTER_READY: ['COPY_READY', 'CANCELED'],
    COPY_READY: ['CREATIVE_READY', 'CANCELED'],
    CREATIVE_READY: ['QUALITY_PASSED', 'CANCELED'],
    QUALITY_PASSED: ['APPROVED', 'CREATIVE_READY', 'CANCELED'],
    APPROVED: ['READY_FOR_SCHEDULING', 'CANCELED'],
    READY_FOR_SCHEDULING: ['TOCA_SCHEDULED', 'CANCELED'],
    TOCA_SCHEDULED: ['PUBLISHED', 'READY_FOR_SCHEDULING', 'CANCELED'],
    PUBLISHED: ['MEASURED'],
    MEASURED: ['ARCHIVED'],
    ARCHIVED: [],
    CANCELED: [],
  },
};

export type EngagementState =
  | 'RECEIVED'
  | 'NORMALIZED'
  | 'CLASSIFIED'
  | 'CONTEXT_RESOLVED'
  | 'RESPONSE_DRAFTED'
  | 'POLICY_CHECKED'
  | 'APPROVED'
  | 'AUTO_ALLOWED'
  | 'SENT'
  | 'PROVIDER_CONFIRMED'
  | 'ESCALATED_TO_HUMAN'
  | 'CLOSED';

export const ENGAGEMENT_LIFECYCLE: StateMachineDefinition<EngagementState> = {
  id: 'R30_SOCIAL_ENGAGEMENT_LIFECYCLE',
  initialState: 'RECEIVED',
  terminalStates: ['PROVIDER_CONFIRMED', 'ESCALATED_TO_HUMAN', 'CLOSED'],
  transitions: {
    RECEIVED: ['NORMALIZED', 'ESCALATED_TO_HUMAN'],
    NORMALIZED: ['CLASSIFIED', 'ESCALATED_TO_HUMAN'],
    CLASSIFIED: ['CONTEXT_RESOLVED', 'ESCALATED_TO_HUMAN', 'CLOSED'],
    CONTEXT_RESOLVED: ['RESPONSE_DRAFTED', 'ESCALATED_TO_HUMAN'],
    RESPONSE_DRAFTED: ['POLICY_CHECKED', 'ESCALATED_TO_HUMAN'],
    POLICY_CHECKED: ['APPROVED', 'AUTO_ALLOWED', 'ESCALATED_TO_HUMAN'],
    APPROVED: ['SENT', 'ESCALATED_TO_HUMAN'],
    AUTO_ALLOWED: ['SENT', 'ESCALATED_TO_HUMAN'],
    SENT: ['PROVIDER_CONFIRMED', 'ESCALATED_TO_HUMAN'],
    PROVIDER_CONFIRMED: [],
    ESCALATED_TO_HUMAN: [],
    CLOSED: [],
  },
};

export type PerformanceLearningState =
  | 'HYPOTHESIS'
  | 'TESTING'
  | 'VALIDATED_PATTERN'
  | 'APPROVAL_REQUIRED'
  | 'APPROVED_LEARNING'
  | 'REJECTED';

export const PERFORMANCE_LEARNING_LIFECYCLE: StateMachineDefinition<PerformanceLearningState> = {
  id: 'R31_PERFORMANCE_FEEDBACK_OPTIMIZATION',
  initialState: 'HYPOTHESIS',
  terminalStates: ['APPROVED_LEARNING', 'REJECTED'],
  transitions: {
    HYPOTHESIS: ['TESTING', 'REJECTED'],
    TESTING: ['VALIDATED_PATTERN', 'REJECTED'],
    VALIDATED_PATTERN: ['APPROVAL_REQUIRED', 'REJECTED'],
    APPROVAL_REQUIRED: ['APPROVED_LEARNING', 'REJECTED'],
    APPROVED_LEARNING: [],
    REJECTED: [],
  },
};

export type RegistryGovernanceState =
  'SCAN' | 'VALIDATE' | 'DIFF' | 'RECONCILE' | 'WRITE_BACK' | 'BLOCKED';

export const REGISTRY_GOVERNANCE_LIFECYCLE: StateMachineDefinition<RegistryGovernanceState> = {
  id: 'R32_MASTER_DATA_AND_REGISTRY_GOVERNANCE',
  initialState: 'SCAN',
  terminalStates: ['WRITE_BACK', 'BLOCKED'],
  transitions: {
    SCAN: ['VALIDATE', 'BLOCKED'],
    VALIDATE: ['DIFF', 'WRITE_BACK', 'BLOCKED'],
    DIFF: ['RECONCILE', 'BLOCKED'],
    RECONCILE: ['VALIDATE', 'WRITE_BACK', 'BLOCKED'],
    WRITE_BACK: [],
    BLOCKED: [],
  },
};

export const STRUCTURAL_LIFECYCLES = [
  SECURITY_LIFECYCLE,
  INCIDENT_LIFECYCLE,
  DISASTER_RECOVERY_LIFECYCLE,
  META_ADS_LIFECYCLE,
  CONTENT_ITEM_LIFECYCLE,
  ENGAGEMENT_LIFECYCLE,
  PERFORMANCE_LEARNING_LIFECYCLE,
  REGISTRY_GOVERNANCE_LIFECYCLE,
] as const;
