import type { McpServer } from '@modelcontextprotocol/server';
import { describe, expect, it, vi } from 'vitest';
import type { PhotoToVideoCandidateManifest } from '../src/contracts/photo-to-video.js';
import {
  registerVideoGenerativeSurface,
  VIDEO_FINALIZE_SCENE_CONTINUATION_TOOL,
  VIDEO_GENERATE_SCENE_CONTINUATION_TOOL,
  VIDEO_OVERLAY_STATIC_GRAPHICS_TOOL,
  VIDEO_TRIM_TOOL,
} from '../src/mcp/video-generative-surface.js';
import type { VideoGenerativeRuntime } from '../src/mcp/video-generative-runtime.js';

type ToolHandler = (input: unknown) => Promise<unknown>;

function captureSurface(runtime: VideoGenerativeRuntime): Map<string, ToolHandler> {
  const handlers = new Map<string, ToolHandler>();
  const server = {
    registerTool(name: string, _definition: unknown, handler: unknown) {
      handlers.set(name, handler as ToolHandler);
    },
  } as unknown as McpServer;
  registerVideoGenerativeSurface(server, () => runtime);
  return handlers;
}

describe('video generative MCP surface', () => {
  it('registers governed generation/finalization and deterministic post-processing tools', () => {
    const handlers = captureSurface(fakeRuntime());
    expect([...handlers.keys()].sort()).toEqual(
      [
        VIDEO_FINALIZE_SCENE_CONTINUATION_TOOL,
        VIDEO_GENERATE_SCENE_CONTINUATION_TOOL,
        VIDEO_OVERLAY_STATIC_GRAPHICS_TOOL,
        VIDEO_TRIM_TOOL,
      ].sort(),
    );
  });

  it('forces the governed scene-continuation route and can return the exact generated bytes', async () => {
    const runtime = fakeRuntime();
    const generate = vi.spyOn(runtime.generation, 'generate');
    const handler = captureSurface(runtime).get(VIDEO_GENERATE_SCENE_CONTINUATION_TOOL);
    expect(handler).toBeDefined();
    const result = await handler!({
      contentItemId: 'CONTENT-TP-1',
      creativeDirection: 'Subtle premium camera motion.',
      returnBase64: true,
    });
    expect(generate).toHaveBeenCalledWith({
      contentItemId: 'CONTENT-TP-1',
      routeType: 'GENERATIVE_SCENE_CONTINUATION_VIDEO',
      creativeDirection: 'Subtle premium camera motion.',
    });
    const structured = (result as { structuredContent: Record<string, unknown> }).structuredContent;
    expect(structured.outputBase64).toBe(Buffer.from([0, 0, 0, 0, 102, 116, 121, 112, 1, 2, 3, 4]).toString('base64'));
    expect(structured.publicationEligible).toBe(false);
  });
});

function fakeRuntime(): VideoGenerativeRuntime {
  const manifest = {
    status: 'GENERATED_REVIEW_REQUIRED',
    outputSha256: 'a'.repeat(64),
    artifactRef: 'gcs://bucket/instagram/item/candidate.mp4',
    provider: 'OPENAI_VIDEO_API',
    providerJobId: 'video_1',
    providerModel: 'sora-2',
  } as unknown as PhotoToVideoCandidateManifest;
  return {
    generation: {
      generate: vi.fn(async () => ({
        outputBytes: Uint8Array.from([0, 0, 0, 0, 102, 116, 121, 112, 1, 2, 3, 4]),
        manifest,
      })),
    } as unknown as VideoGenerativeRuntime['generation'],
    finalization: {
      finalize: vi.fn(),
    } as unknown as VideoGenerativeRuntime['finalization'],
    postProcessor: {
      trim: vi.fn(),
      overlayStaticGraphics: vi.fn(),
    } as unknown as VideoGenerativeRuntime['postProcessor'],
  };
}
